name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install PurgeCSS
      run: |
        npm install -g purgecss
    # intentionally absent from the Makefile due to destructive behavior
    - name: Strip unused CSS
      run: |
        purgecss -c scripts/purgecss.config.js -con templates/*.tmpl -css static/css/* -o static/css/
#    - name: Run tests
#      run: |
#        pip install pytest
#        make test
    - name: Build project
      run: |
        make dist
    - name: Copy build artifacts
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.COFFEE_HOSTNAME }}
        username: ${{ secrets.COFFEE_SSH_USER }}
        key: ${{ secrets.COFFEE_SSH_KEY }}
        source: dist/*
        strip_components: 1
        target: /home/${{ secrets.COFFEE_SSH_USER }}/
    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.COFFEE_HOSTNAME }}
        username: ${{ secrets.COFFEE_SSH_USER }}
        key: ${{ secrets.COFFEE_SSH_KEY }}
        script: |
          sudo systemctl restart coffee-web
